In [2]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista)

array([1, 2, 3])

In [7]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#Numero pares
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
arr = np.zeros(6)

In [10]:
arr

array([0., 0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros((5, 5))

In [12]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [18]:
np.random.rand(5)

array([0.79820265, 0.02062003, 0.35570707, 0.81642866, 0.50035638])

In [19]:
np.random.rand(5) * 100

array([46.44800014, 52.29927998, 61.41955281, 29.92388181, 10.23114643])

In [20]:
np.random.rand(5, 4)

array([[0.25092661, 0.3920187 , 0.97712828, 0.82487381],
       [0.73049624, 0.68941049, 0.31099575, 0.82058218],
       [0.27696171, 0.35973488, 0.07970371, 0.31656654],
       [0.8430198 , 0.66135275, 0.31432574, 0.13166518],
       [0.03551487, 0.57434384, 0.50654705, 0.9608407 ]])

In [21]:
np.random.rand(5, 4, 3)

array([[[0.17174975, 0.37121198, 0.25151557],
        [0.0737826 , 0.86822004, 0.06887094],
        [0.77486648, 0.45308883, 0.07316806],
        [0.29371473, 0.19579306, 0.15927554]],

       [[0.35724918, 0.69444413, 0.6506509 ],
        [0.68412813, 0.55622183, 0.61382446],
        [0.299668  , 0.77653665, 0.58880635],
        [0.65689325, 0.28795241, 0.11518984]],

       [[0.15635818, 0.73865598, 0.0896098 ],
        [0.47840934, 0.57753952, 0.47456567],
        [0.43060436, 0.12829685, 0.04272053],
        [0.81569319, 0.95697304, 0.8798654 ]],

       [[0.5970003 , 0.60544165, 0.53266505],
        [0.82048561, 0.38983467, 0.34449814],
        [0.93919109, 0.60073491, 0.61247659],
        [0.17554944, 0.84859309, 0.67241437]],

       [[0.59684355, 0.71353543, 0.79338817],
        [0.15918275, 0.63939731, 0.8916107 ],
        [0.70525086, 0.6684286 , 0.80150441],
        [0.44847164, 0.64013883, 0.76644438]]])

In [22]:
np.random.randn(4)

array([-1.26632476,  1.61655159,  0.86014928, -0.54264377])

In [23]:
np.random.randint(0, 100, 10)

array([13, 97,  3, 51,  7, 45, 98, 74, 93, 67])

In [25]:
arr = np.random.rand(25)

In [26]:
arr

array([0.09664972, 0.77608292, 0.23740218, 0.7256983 , 0.65094068,
       0.90887712, 0.18371221, 0.96226552, 0.22506135, 0.57990183,
       0.9298003 , 0.69500521, 0.96307573, 0.61359131, 0.93543017,
       0.56142982, 0.93456305, 0.8314201 , 0.62053101, 0.01031268,
       0.98351132, 0.62792843, 0.02325396, 0.40114743, 0.16709824])

In [27]:
arr.reshape((5, 5))

array([[0.09664972, 0.77608292, 0.23740218, 0.7256983 , 0.65094068],
       [0.90887712, 0.18371221, 0.96226552, 0.22506135, 0.57990183],
       [0.9298003 , 0.69500521, 0.96307573, 0.61359131, 0.93543017],
       [0.56142982, 0.93456305, 0.8314201 , 0.62053101, 0.01031268],
       [0.98351132, 0.62792843, 0.02325396, 0.40114743, 0.16709824]])

In [29]:
arr = arr.reshape((5, 5))

In [30]:
arr.shape

(5, 5)

In [32]:
arr.max()

0.9835113208888823

In [33]:
arr.min()

0.010312676146482014

In [34]:
arr.argmax()

20

In [35]:
arr.argmin()

19