In [1]:
# Importando a bilioteca Numpy.
import numpy as np

In [2]:
arr = np.arange(0, 30, 3)

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
# Pegando um element e passando como parâmetro dentro dos colchetes o índice desejado.
# Se eu quiser pegar o número 9.
arr[3]

9

In [6]:
# Pegando multiplos elementos do meu array.
# Puxar do segundo índice até o final.
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
# Alterando todos os valores a partir do índice 2 em diante.
arr[2:] = 100

In [8]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
# Array bidimencionais.
# Criando um array de duas dimensões.
arr = np.arange(50).reshape(5, 10)

In [10]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])