In [1]:
# Importando a bilioteca Numpy.
import numpy as np

In [4]:
arr = np.arange(0, 30, 3)

In [5]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
# Pegando um element e passando como parâmetro dentro dos colchetes o índice desejado.
# Se eu quiser pegar o número 9.
arr[3]

9

In [7]:
# Pegando multiplos elementos do meu array.
# Puxar do segundo índice até o final.
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
# Alterando todos os valores a partir do índice 2 em diante.
arr[2:] = 100

In [9]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
# Array bidimencionais.
# Criando um array de duas dimensões.
arr = np.arange(50).reshape(5, 10)

In [11]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
# Verificando o tanho dele.
# Resultado: Array de 5 linhas 10 colunas.
arr.shape

(5, 10)

In [14]:
# Agora vou fatiar (slaces) desse array. (apenas 1 colchete).
# Informações que eu quero nas linhas.
# Eu quero buscar as informações até a terceira linha.
# Ou seja, o primeiro colchete faz mensão as linhas | E o segundo faz mensão as colunas.
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
# Vou criar outro array. Mas, vou dizer que esse meu arr2 vai conter até a terceira linha do meu arr1
arr2 = arr[:3]

In [16]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
# Observação:
# Se eu fizer isso.
# arr2[:3] = 100 = aqui estou inserindo o valor 100 no enlace que eu defini e automaticamente mudando os
# valores do (arr), pra eu não adicionar ou fazer um erro, vou mostrar do jeito correto.
# Ao invés de digitar arr2[:3] = 100 eu faço da seguinte forma: arr2 = arr[:3].copy, dess amaneira, as informações
# do enlace do arr continuam e não se alteram.
# Vamos para o exemplo.
arr2 = arr[:3].copy()

In [18]:
arr2[:] = 100

In [19]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [20]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [23]:
# Denotação de vírgula, quando se usa 1 colchete.
# Onde a vírgula se usa para encontrar ou separar fatias (linhas) de 2 dimensões arr[|,]. E após a vírgula nas colunas.
# Exemplo: Se eu quiser encontrar todos os elementos entre a linha 1 e 3 e da coluna 5 em diante.
# [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
# [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
# [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])